enchant.loader.setRootPath("");

enchant.loader.setAnimation("Smoke01", 
    {"dependencies":{"animations":[],"images":["test"]},"timelines":[{"position":[],"scale":[{"duration":5,"endValue":[1.10000002384186,1.10000002384186],"tween":true,"startValue":[0.5,0.5],"frameNo":0},{"duration":9,"endValue":[1.5,1.5],"tween":true,"startValue":[1.10000002384186,1.10000002384186],"frameNo":5},{"duration":1,"endValue":[1.5,1.5],"startValue":[1.5,1.5],"frameNo":14}],"hue":[],"source":[{"duration":15,"center":[0,0],"id":"test","type":"image","frameNo":0,"rect":[0,0,32,32],"relative":false},{"duration":1,"id":"","rect":null}],"rotation":[{"duration":14,"endValue":30,"tween":true,"startValue":0,"frameNo":0},{"duration":1,"endValue":30,"startValue":30,"frameNo":14}],"alpha":[{"duration":14,"endValue":0.0,"tween":true,"startValue":1.0,"frameNo":0},{"duration":1,"endValue":0.0,"startValue":0.0,"frameNo":14}]}]}
);
enchant.loader.setAnimation("SmokeRing", 
    {"dependencies":{"animations":["Smoke01"],"images":["test"]},"timelines":[{"position":[{"duration":4,"endValue":[22,22],"tween":true,"startValue":[0,0],"frameNo":0},{"duration":11,"endValue":[22,22],"startValue":[22,22],"frameNo":4}],"scale":[],"hue":[],"source":[{"duration":15,"emitter":false,"id":"Smoke01","type":"animation","frameNo":0,"relative":false},{"duration":1,"id":"","rect":null}],"rotation":[],"alpha":[]},{"position":[{"duration":4,"endValue":[-22,22],"tween":true,"startValue":[0,0],"frameNo":0},{"duration":11,"endValue":[-22,22],"startValue":[-22,22],"frameNo":4}],"scale":[],"hue":[],"source":[{"duration":15,"emitter":false,"id":"Smoke01","type":"animation","frameNo":0,"relative":false},{"duration":1,"id":"","rect":null}],"rotation":[],"alpha":[]},{"position":[{"duration":4,"endValue":[0,30],"tween":true,"startValue":[0,0],"frameNo":0},{"duration":11,"endValue":[0,30],"startValue":[0,30],"frameNo":4}],"scale":[],"hue":[],"source":[{"duration":15,"emitter":false,"id":"Smoke01","type":"animation","frameNo":0,"relative":false},{"duration":1,"id":"","rect":null}],"rotation":[],"alpha":[]},{"position":[{"duration":4,"endValue":[0,-30],"tween":true,"startValue":[0,0],"frameNo":0},{"duration":11,"endValue":[0,-30],"startValue":[0,-30],"frameNo":4}],"scale":[],"hue":[],"source":[{"duration":15,"emitter":false,"id":"Smoke01","type":"animation","frameNo":0,"relative":false},{"duration":1,"id":"","rect":null}],"rotation":[],"alpha":[]},{"position":[{"duration":4,"endValue":[22,-22],"tween":true,"startValue":[0,0],"frameNo":0},{"duration":11,"endValue":[22,-22],"startValue":[22,-22],"frameNo":4}],"scale":[],"hue":[],"source":[{"duration":15,"emitter":false,"id":"Smoke01","type":"animation","frameNo":0,"relative":false},{"duration":1,"id":"","rect":null}],"rotation":[],"alpha":[]},{"position":[{"duration":4,"endValue":[30,0],"tween":true,"startValue":[0,0],"frameNo":0},{"duration":11,"endValue":[30,0],"startValue":[30,0],"frameNo":4}],"scale":[],"hue":[],"source":[{"duration":15,"emitter":false,"id":"Smoke01","type":"animation","frameNo":0,"relative":false},{"duration":1,"id":"","rect":null}],"rotation":[],"alpha":[]},{"position":[{"duration":4,"endValue":[-30,0],"tween":true,"startValue":[0,0],"frameNo":0},{"duration":11,"endValue":[-30,0],"startValue":[-30,0],"frameNo":4}],"scale":[],"hue":[],"source":[{"duration":15,"emitter":false,"id":"Smoke01","type":"animation","frameNo":0,"relative":false},{"duration":1,"id":"","rect":null}],"rotation":[],"alpha":[]},{"position":[{"duration":4,"endValue":[-22,-22],"tween":true,"startValue":[0,0],"frameNo":0},{"duration":11,"endValue":[-22,-22],"startValue":[-22,-22],"frameNo":4}],"scale":[],"hue":[],"source":[{"duration":15,"emitter":false,"id":"Smoke01","type":"animation","frameNo":0,"relative":false},{"duration":1,"id":"","rect":null}],"rotation":[],"alpha":[]}]}
);
enchant.loader.setAnimation("SingleSpinAxe", 
    {"dependencies":{"animations":[],"images":["Battle/Skills/Weapon_AxeBase"]},"timelines":[{"position":[{"duration":7,"endValue":[0,0],"startValue":[0,0],"frameNo":0},{"duration":7,"endValue":[0,0],"startValue":[0,0],"frameNo":7}],"scale":[],"hue":[],"source":[{"duration":7,"center":[0,0],"id":"Battle/Skills/Weapon_AxeBase","type":"image","frameNo":0,"rect":[0,0,32,32],"relative":false}],"rotation":[{"duration":7,"endValue":315,"tween":true,"startValue":0,"frameNo":0},{"duration":7,"endValue":315,"startValue":315,"frameNo":7}],"alpha":[]}]}
);
enchant.loader.setAnimation("CycloneAxe", 
    {"dependencies":{"animations":["Battle/Skills/Battler/SmallJump","Battle/Skills/Axe/SpinAxeY"],"images":["Battle/Skills/Battler_Base","Battle/Skills/Weapon_AxeBase"]},"timelines":[{"position":[{"duration":2,"endValue":[0,0],"startValue":[0,0],"frameNo":0},{"duration":10,"endValue":[-16,0],"tween":true,"startValue":[0,0],"frameNo":2},{"duration":5,"endValue":[-16,0],"startValue":[-16,0],"frameNo":12},{"duration":10,"endValue":[0,0],"tween":true,"startValue":[-16,0],"frameNo":17},{"duration":19,"endValue":[0,0],"startValue":[0,0],"frameNo":27}],"scale":[],"hue":[],"source":[{"duration":28,"emitter":false,"id":"Battle/Skills/Battler/SmallJump","type":"animation","frameNo":0,"relative":false},{"duration":18,"center":[0,0],"id":"Battle/Skills/Battler_Base","type":"image","frameNo":28,"rect":[288,0,32,32],"relative":false}],"rotation":[],"alpha":[]},{"position":[{"duration":7,"wait":true,"frameNo":0},{"duration":13,"endValue":[0,0],"tween":true,"startValue":[-8,-36],"frameNo":7},{"duration":21,"endValue":[0,0],"tween":true,"startValue":[0,0],"frameNo":20},{"duration":41,"endValue":[0,0],"tween":true,"startValue":[0,0],"frameNo":41}],"scale":[],"hue":[],"source":[{"duration":7,"wait":true,"frameNo":0},{"duration":41,"emitter":false,"id":"Battle/Skills/Axe/SpinAxeY","type":"animation","frameNo":7,"relative":false}],"rotation":[],"alpha":[]}]}
);

